apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - knative-serving.yaml
  - local-gateway.yaml

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: knative-serving
