apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    app.kubernetes.io/part-of: mlops-platform
    app.kubernetes.io/component: autoscaler
