#!/usr/bin/env bash
# =============================================================================
# argo-cd/post-apply.sh — bootstrap the GitOps loop after ArgoCD core is up
# =============================================================================
# Why split from kustomization.yaml resources:
#   `app-of-apps.yaml` defines THREE resources owned by ArgoCD itself:
#     - AppProject/platform                        (cluster-wide policy)
#     - Application/app-of-apps (self-managed)     (reconciles this directory)
#     - ApplicationSet/platform-components         (fans out to platform/*)
#
#   These are bootstrap manifests — they cannot live in the kustomization
#   resources list because the `platform-gitops` Application (generated by
#   ApplicationSet/platform-components itself) reconciles
#   `platform/components/gitops/` which traverses into `argo-cd/` and
#   re-emits the same AppProject + ApplicationSet. ArgoCD then reports
#   `SharedResourceWarning` ("resource is part of applications gitops/
#   platform-gitops and app-of-apps") and flips platform-gitops to
#   Degraded forever. (Field-observed 2026-05-11.)
#
#   The clean shape: kustomization owns only `install.yaml` (+ patches);
#   this hook applies `app-of-apps.yaml` once via `kubectl apply -f` after
#   the controllers are Ready, closing the GitOps loop.
#
# Idempotent: re-running re-applies the same three manifests; ArgoCD's
# resource finalizers prevent accidental garbage collection on re-apply.
# =============================================================================
set -euo pipefail

NS=gitops
COMPONENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_OF_APPS="${COMPONENT_DIR}/app-of-apps.yaml"

if [[ ! -f "$APP_OF_APPS" ]]; then
  echo "ERROR: $APP_OF_APPS not found" >&2
  exit 2
fi

# Block until the three ArgoCD controllers are Ready. Without this the
# `kubectl apply` below races the CRD registration + admission webhooks
# (Application CRD may not yet be served by the apiserver).
echo "    [post-apply] waiting argocd-server / argocd-repo-server / argocd-application-controller Ready (timeout 600s)"
kubectl -n "$NS" rollout status deploy/argocd-server                      --timeout=600s
kubectl -n "$NS" rollout status deploy/argocd-repo-server                 --timeout=600s
kubectl -n "$NS" rollout status statefulset/argocd-application-controller --timeout=600s

# Wait for Application CRD to be served (rollout-status Ready is not
# sufficient — the controller registers CRDs after pod boot).
echo "    [post-apply] waiting Application CRD established (timeout 120s)"
kubectl wait --for=condition=established --timeout=120s \
  crd/applications.argoproj.io \
  crd/applicationsets.argoproj.io \
  crd/appprojects.argoproj.io

echo "    [post-apply] applying app-of-apps.yaml (AppProject + self-managed root + ApplicationSet)"
kubectl apply --server-side --force-conflicts -f "$APP_OF_APPS"
