apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - airflow
  - flink
  - great-expectations
  - spark
  - superset/deployment.yaml
  - superset/scaledobject.yaml
  - trino/deployment.yaml
  - trino/hpa.yaml
