#!/usr/bin/env -S uv run python
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Generate platform/services/base/kustomization.yaml from config/services.yaml.

Reads `config/services.yaml` and emits `services/base/kustomization.yaml`
listing only resources whose owning service has `enabled: true`. Always-on
infra (ConfigMap, RBAC, HPA) is unconditionally included.

Usage:
    uv run python scripts/generate_kustomization.py            # write file
    uv run python scripts/generate_kustomization.py --dry-run  # stdout only

Mirrors the use-case-side generator's contract so `make configure` and
`make generate-kustomization` are uniform across the platform and
use-case repos.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = REPO_ROOT / "config" / "services.yaml"
OUTPUT_PATH = REPO_ROOT / "services" / "base" / "kustomization.yaml"

ALWAYS_INCLUDED = [
    "configmaps/pipeline-infrastructure.yaml",
    "rbac/roles.yaml",
    "rbac/bindings.yaml",
    "hpa/autoscaling.yaml",
]

# (category, service_key) → ordered list of resource paths under services/base/
SERVICE_RESOURCES: dict[tuple[str, str], list[str]] = {
    ("ingestion", "rest_collector"): [
        "deployments/rest-collector.yaml",
        "cronjobs/ingestion.yaml",
    ],
    ("ingestion", "websocket_collector"): [
        "deployments/websocket-collector.yaml",
    ],
    ("ingestion", "backfill"): ["cronjobs/backfill.yaml"],
    ("ingestion", "supplementary"): ["cronjobs/supplementary.yaml"],
    ("quality", "validator"): ["deployments/validator.yaml"],
    ("quality", "analyzer"): ["deployments/analyzer.yaml"],
    ("processing", "batch"): [
        "deployments/batch-processing.yaml",
        "cronjobs/batch-features.yaml",
    ],
    ("processing", "feature_engine"): ["deployments/feature-engine.yaml"],
    # ADR-023/025: FlinkDeployment CR is owned by each use-case overlay,
    # so the Flink job has no resource template here.
    ("processing", "flink_job"): [],
    ("processing", "vector"): [
        "deployments/vector-processing.yaml",
        "cronjobs/vector-embedding.yaml",
    ],
    ("training", "trainer"): ["cronjobs/training.yaml"],
    ("training", "drift"): ["cronjobs/drift-multi-scale.yaml"],
    ("serving", "gateway"): ["deployments/gateway.yaml"],
    ("serving", "feature_cache"): ["deployments/feature-cache.yaml"],
    ("serving", "inference_engine"): ["deployments/inference-engine.yaml"],
    ("automation", "materialization"): ["cronjobs/materialization.yaml"],
    ("automation", "retraining"): ["cronjobs/retraining.yaml"],
    ("dashboard", "backend"): ["deployments/dashboard-backend.yaml"],
    ("dashboard", "frontend"): ["deployments/dashboard-frontend.yaml"],
    ("dashboard", "ml_bridge"): ["deployments/ml-bridge.yaml"],
}

CATEGORY_HEADERS = {
    "ingestion": "INGESTION — Data collection",
    "quality": "QUALITY — Data validation",
    "processing": "PROCESSING — Feature engineering",
    "training": "TRAINING — Model training + drift detection",
    "serving": "SERVING — Model inference API",
    "automation": "AUTOMATION — Pipeline orchestration",
    "dashboard": "DASHBOARD — Web UI",
}

CATEGORY_ORDER = [
    "ingestion",
    "quality",
    "processing",
    "training",
    "serving",
    "automation",
    "dashboard",
]

HEADER = """\
# =============================================================================
# MICROSERVICE TEMPLATES — Full End-to-End ML Pipeline (AUTO-GENERATED)
# =============================================================================
# Generated by: uv run python scripts/generate_kustomization.py
# Source:       config/services.yaml (enabled flags)
#
# To regenerate after toggling services: make generate-kustomization
#
# Generic deployment/cronjob templates with NO domain-specific values.
# All configuration comes from the use-case's pipeline-config ConfigMap.
# Use-case overlays add namePrefix, namespace, image mappings, and patches.
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
"""

FOOTER_LABELS = """
labels:
  - pairs:
      app.kubernetes.io/component: ml-pipeline
      app.kubernetes.io/part-of: mlops-platform
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
"""


def render(config: dict) -> str:
    services_cfg = config.get("services") or {}
    enabled_total = 0
    disabled_total = 0
    body: list[str] = []

    body.append("  # ===========================================================================")
    body.append("  # CONFIGMAP / RBAC / HPA — always included")
    body.append("  # ===========================================================================")
    for path in ALWAYS_INCLUDED:
        body.append(f"  - {path}")
    body.append("")

    for category in CATEGORY_ORDER:
        cat_services = services_cfg.get(category, {})
        if not cat_services:
            continue
        body.append("  # ===========================================================================")
        body.append(f"  # {CATEGORY_HEADERS[category]}")
        body.append("  # ===========================================================================")
        any_enabled = False
        for service_key, service_meta in cat_services.items():
            enabled = bool(service_meta.get("enabled", False))
            paths = SERVICE_RESOURCES.get((category, service_key), [])
            if enabled:
                enabled_total += 1
                if not paths:
                    body.append(f"  # {service_key}: enabled (no template — owned by use-case overlay)")
                    continue
                any_enabled = True
                body.append(f"  # {service_key}")
                for p in paths:
                    body.append(f"  - {p}")
            else:
                disabled_total += 1
                body.append(f"  # {service_key}: DISABLED (config/services.yaml)")
        if not any_enabled:
            body.append(f"  # (all {category} services disabled)")
        body.append("")

    summary = f"# Services: {enabled_total} enabled, {disabled_total} disabled\n"
    return summary + HEADER + "\n".join(body) + FOOTER_LABELS


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print to stdout, do not write the file",
    )
    args = parser.parse_args()

    if not CONFIG_PATH.exists():
        print(f"error: {CONFIG_PATH} not found", file=sys.stderr)
        return 1

    with CONFIG_PATH.open() as f:
        config = yaml.safe_load(f)

    rendered = render(config)

    if args.dry_run:
        sys.stdout.write(rendered)
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered)
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
