apiVersion: v1
kind: Namespace
metadata:
  name: data-governance
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    app.kubernetes.io/part-of: mlops-platform
    app.kubernetes.io/component: data-governance
    istio-injection: enabled
